export type RootStackParamList = {
  Splash: undefined;
  LanguageSelection: undefined;
  Login: undefined;
  OtpVerification: { mobileNumber: string; mockOtp?: string };
  RoleSelection: { isEdit?: boolean } | undefined;
  RetailShopListing: undefined;
  FarmerMarketplace: undefined;
  ServiceWorkerListing: undefined;
  RentalMarketplace: undefined;
  DailyWageJobListing: undefined;
  NearbyHelp: undefined;
  RetailerDashboard: undefined;
  FarmerDashboard: undefined;
  WorkerDashboard: undefined;
  RentalDashboard: undefined;
  AddProduct: { productId?: string } | undefined;
  AddCrop: { cropId?: string } | undefined;
  AddRental: { rentalId?: string } | undefined;
  AddOffer: undefined;
  WorkerDetails: { workerId: string; workerName: string };
  ShopDetails: { shopId: string; shopName: string };
  MainTabs: undefined;
  Profile: undefined;
  Settings: undefined;
  Subscription: undefined;
  EmployerDashboard: undefined;
  AddJob: { jobId?: string } | undefined;
  CreateProfile: { isEdit?: boolean } | undefined;
  Notifications: undefined;
  HelpSupport: undefined;
};
